# application.yml (Configuration example)
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    driver-class-name: oracle.jdbc.OracleDriver
    username: your_username
    password: your_password

    # HikariCP specific settings
    hikari:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@localhost:1521:XE
      username: your_username
      password: your_password
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

# Hierarchical Cache Configuration
#hierarchical:
#  cache:
#    caffeine:
#      maximum-size: 10000
#      expire-after-write: 10m
#      expire-after-access: 5m
#      record-stats: true
#    redis:
#      address: redis://localhost:6379
#      connection-pool-size: 64
#      connection-minimum-idle-size: 10
#      timeout: 3000
#      default-ttl: 1h

# Logging configuration
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.example.cache: DEBUG

hierarchical:
  cache:
    caffeine:
      maximum-size: 10000
      expire-after-write: PT10M
      expire-after-access: PT5M
      record-stats: true
    redis:
      address: redis://localhost:6379
      password: null
      connection-pool-size: 64
      connection-minimum-idle-size: 10
      timeout: 3000
      default-ttl: PT1H
    levels:
      level_1:
        name: "Level 1 Cache"
        maximum-size: 5000
        ttl: PT15M
        enable-l1: true
        enable-l2: true
      level_2:
        name: "Level 2 Cache"
        maximum-size: 2000
        ttl: PT30M
        enable-l1: true
        enable-l2: true
      level_3:
        name: "Level 3 Cache"
        maximum-size: 1000
        ttl: PT1H
        enable-l1: false
        enable-l2: true